# START

BasicPodmindLambdaRole01:
  Type: AWS::IAM::Role
  Properties:
    RoleName: BasicPodmindLambdaRole01
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action: sts:AssumeRole
    Policies:
      - PolicyName: LambdaDynamoDBAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: 
                - arn:aws:dynamodb:us-east-1:975049884289:table/SysUser.${self:provider.stage,"dev"}
                - arn:aws:dynamodb:us-east-1:975049884289:table/SysLogin.${self:provider.stage,"dev"}
                - arn:aws:dynamodb:us-east-1:975049884289:table/PdmPodcast.${self:provider.stage,"dev"}
                - arn:aws:dynamodb:us-east-1:975049884289:table/PdmEpisode.${self:provider.stage,"dev"}
                - arn:aws:dynamodb:us-east-1:975049884289:table/PdmWidget.${self:provider.stage,"dev"}
                - arn:aws:dynamodb:us-east-1:975049884289:table/PdmChat.${self:provider.stage,"dev"}
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
                - s3:ListBucket
              Resource:
                - arn:aws:s3:::podmind01-backend01-file01-${self:provider.stage,"dev"}/*
                - arn:aws:s3:::podmind01-backend01-file01-${self:provider.stage,"dev"}

    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

# END
