# START


FileBucket01:
  Type: AWS::S3::Bucket
  DeletionPolicy: Retain
  Properties:
    OwnershipControls:
      Rules:
        - ObjectOwnership: ObjectWriter
    BucketName: podmind01-backend01-file01-${self:provider.stage}
    
TableSysUser:
  Type: AWS::DynamoDB::Table
  DeletionPolicy: Retain
  Properties:
    TableName: 'SysUser.${self:provider.stage,"dev"}'
    BillingMode: "PAY_PER_REQUEST"
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: "true"
    DeletionProtectionEnabled: true
    AttributeDefinitions:
      - AttributeName: "id"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "id"
        KeyType: HASH



TableSysLogin:
  Type: AWS::DynamoDB::Table
  DeletionPolicy: Retain
  Properties:
    TableName: 'SysLogin.${self:provider.stage,"dev"}'
    BillingMode: "PAY_PER_REQUEST"
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: "true"
    DeletionProtectionEnabled: true
    AttributeDefinitions:
      - AttributeName: "id"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "id"
        KeyType: HASH



TablePdmPodcast:
  Type: AWS::DynamoDB::Table
  DeletionPolicy: Retain
  Properties:
    TableName: 'PdmPodcast.${self:provider.stage,"dev"}'
    BillingMode: "PAY_PER_REQUEST"
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: "true"
    DeletionProtectionEnabled: true
    AttributeDefinitions:
      - AttributeName: "id"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "id"
        KeyType: HASH



TablePdmEpisode:
  Type: AWS::DynamoDB::Table
  DeletionPolicy: Retain
  Properties:
    TableName: 'PdmEpisode.${self:provider.stage,"dev"}'
    BillingMode: "PAY_PER_REQUEST"
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: "true"
    DeletionProtectionEnabled: true
    AttributeDefinitions:
      - AttributeName: "id"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "id"
        KeyType: HASH



TablePdmWidget:
  Type: AWS::DynamoDB::Table
  DeletionPolicy: Retain
  Properties:
    TableName: 'PdmWidget.${self:provider.stage,"dev"}'
    BillingMode: "PAY_PER_REQUEST"
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: "true"
    DeletionProtectionEnabled: true
    AttributeDefinitions:
      - AttributeName: "id"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "id"
        KeyType: HASH



TablePdmChat:
  Type: AWS::DynamoDB::Table
  DeletionPolicy: Retain
  Properties:
    TableName: 'PdmChat.${self:provider.stage,"dev"}'
    BillingMode: "PAY_PER_REQUEST"
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: "true"
    DeletionProtectionEnabled: true
    AttributeDefinitions:
      - AttributeName: "id"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "id"
        KeyType: HASH


QueueAimIngestTranscribeEpisode:
  Type: "AWS::SQS::Queue"
  Properties:
    QueueName: 'aim_ingest-transcribe_episode-${self:provider.stage,"dev"}'

QueueAimIngestEmbedChunk:
  Type: "AWS::SQS::Queue"
  Properties:
    QueueName: 'aim_ingest-embed_chunk-${self:provider.stage,"dev"}'

QueueAimIngestStoreEmbed:
  Type: "AWS::SQS::Queue"
  Properties:
    QueueName: 'aim_ingest-store_embed-${self:provider.stage,"dev"}'


BasicPodmindLambdaRole01:
  Type: AWS::IAM::Role
  Properties:
    RoleName: BasicPodmindLambdaRole01
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action: sts:AssumeRole
    Policies:
      - PolicyName: LambdaDynamoDBAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: 
                - arn:aws:dynamodb:us-east-1:975049884289:table/SysUser.${self:provider.stage,"dev"}
                - arn:aws:dynamodb:us-east-1:975049884289:table/SysLogin.${self:provider.stage,"dev"}
                - arn:aws:dynamodb:us-east-1:975049884289:table/PdmPodcast.${self:provider.stage,"dev"}
                - arn:aws:dynamodb:us-east-1:975049884289:table/PdmEpisode.${self:provider.stage,"dev"}
                - arn:aws:dynamodb:us-east-1:975049884289:table/PdmWidget.${self:provider.stage,"dev"}
                - arn:aws:dynamodb:us-east-1:975049884289:table/PdmChat.${self:provider.stage,"dev"}
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
                - s3:ListBucket
              Resource:
                - arn:aws:s3:::podmind01-backend01-file01-${self:provider.stage,"dev"}/*
                - arn:aws:s3:::podmind01-backend01-file01-${self:provider.stage,"dev"}

    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

# END
